name: github_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.5
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  http: ^1.1.0
  hive: ^2.2.3
  built_value: ^8.6.2
  flutter_svg: ^2.0.9
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svgs/
    - assets/translations/
